.node_docker:
  timeout: "10m"
  image: node:lts-alpine

variables:
  YARN_CACHE_FOLDER: &yarn_cache_path "$CI_PROJECT_DIR/.yarn_cache_$CI_PROJECT_NAME"

cache:
  key: "$CI_PROJECT_NAME_yarn_node_cache-$CI_COMMIT_REF_SLUG"
  paths:
    - *yarn_cache_path

before_script:
  - yarn install --frozen-lockfile --non-interactive --link-duplicates

stages:
  - lint
  - build
  - test
  - deploy

lint:
  stage: lint
  extends: .node_docker
  script: yarn lint

build:
  stage: build
  extends: .node_docker
  script: yarn build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - builders/
    expire_in: 30 days


deploy_dry_run:
  stage: test
  extends: .node_docker
  script:
    - npm publish --dry-run --access public
  dependencies:
    - build

deploy-release:
  stage: deploy
  extends: .node_docker
  only:
      refs:
          - '/^tags\/v(\d+\.\d+\.\d+)$/'
  script: npm publish --access public
  when: manual
  dependencies:
    - build
  allow_failure: false

deploy-release-candidate:
    stage: deploy
    extends: .node_docker
    only:
        refs:
            - '/^tags\/v(\d+\.\d+\.\d+)-rc\.\d{1,3}$/'
    script: npm publish --tag rc --access public
    when: manual
    dependencies:
        - build
    allow_failure: false

deploy-alpha:
    stage: deploy
    extends: .node_docker
    only:
        refs:
            - '/^tags\/v(\d+\.\d+\.\d+)-alpha\.\d{1,3}$/'
    script: npm publish --tag alpha --access public
    when: manual
    dependencies:
        - build
    allow_failure: false

